apiVersion: v1
kind: Service
metadata:
  name: minikube-example-svc
  namespace: default
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: minikube-example
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 32001